### ISSUE TITLE
Ajouter un logo

### ISSUE THREAD

**Issue by kdelfour** [OkoWe/okowe.github.io#12]
@lnghc Il nous faudra un logo pour le site.
Pour le mettre en favicon.ico, et l'inserer dans le site également.

**Comment by RoToRx88** [comment]
Clément et Lucie travaillent sur un proto de logo.
@lnghc est en attente du fichier final du logo pour le logo actuel.

**Comment by kdelfour** [comment]
@RoToRx88 Des news du logo ?

**Comment by lnghc** [comment]
Icônes comment ca marche envoyés à Nicolas depuis un moment.
Pour le logo je viens de recevoir un mail j'attend qu'il charge et je
reviens vers vous.

**Comment by RoToRx88** [comment]
@lnghc Tu devrais aussi recevoir dans le WE une proposition de la part de Clément et Lucie qui ont travaillés dessus.
