### ISSUE TITLE
Formulation phrase d'accroche mailling

### ISSUE THREAD

**Issue by RoToRx88** [OkoWe/okowe.github.io#6]
La formulation de la phrase d'accroche pour le mailing est jugé trop agressif.

Voir avec @lnghc pour une formulation plus douce.

**Comment by kdelfour** [comment]
@lnghc Si tu as des idées, je suis preneur. 
J'ai mis "SUIVEZ AVEC NOUS L'AVENTURE OKO WE !" mais si tu as mieux...

**Comment by lnghc** [comment]
Hello les guys, 

bien reçu vos mails mais impossible de me connecter sur github qui rame ….
La connexion avec 3G est naz et je n’ai pas de wifi aujourd’hui.

Je pars cette aprem pour Cassou, le village dans lequel je bosse et aucune idée de la connexion que je vais avoir!

Pour toutes les idées que j’ai eu, j’ai envoyé les détails à Nicolas que ce soit les couleur, les typos, les idées de phrases d’accroche qu’il confère ces mails du 6 juillet et du 17 Juillet.

Si vous avez d’autre idées, des préférences il va falloir me les écrire par mail car je ne reçoit rien sur github.
Des photos avec whatsapp par exemple pour un aperçu.
On ne peut mieux faire!

Bonne journée à tous les deux,

Hélène
L’Indiana Josette du Burkina!

**Comment by RoToRx88** [comment]
@kdelfour dit moi ce qu'il te manque que je cherche ca dans mes mails.

@lnghc Quand nous répondons sur une issue github tu reçois un mail et tu n'as qu'à y répondre pour que ca poste sur github automatiquement il me semble.

**Comment by kdelfour** [comment]
@RoToRx88 @lnghc J'ai changé la phrase du mailing, mais faudra me dire si ca vous va ou pas.
Pour le reste, ouvre des issues avec les changements qu'on puissent avancer comme ça.
