### ISSUE TITLE
Couleur du fond

### ISSUE THREAD

**Issue by RoToRx88** [OkoWe/okowe.github.io#7]
Remplacer le fond noir des pages par la couleur suivante:

RGB: 84; 89; 112
html: #545970

**Comment by kdelfour** [comment]
Sur quel page ? Tu parles du noir derrière "Missions" ?

**Comment by RoToRx88** [comment]
Je pense. @lnghc tu confirmes ?

**Comment by lnghc** [comment]
Je confirme pour la page comment ça marche?,
RGB : 84; 89; 112
